@{
    Id                 = "dracula"
    DisplayName        = "Dracula"
    DarkMode           = $true
    VSCodeExtension    = "dracula-theme.theme-dracula"
    VSCodeThemeName    = "Dracula"
    StarshipPalette    = "dracula"
    TerminalColors     = @{
        name                = "DOTMOD Dracula"
        background          = "#282a36"
        foreground          = "#f8f8f2"
        selectionBackground = "#44475a"
        cursorColor         = "#f8f8f2"
        black               = "#21222c"
        red                 = "#ff5555"
        green               = "#50fa7b"
        yellow              = "#f1fa8c"
        blue                = "#bd93f9"
        purple              = "#ff79c6"
        cyan                = "#8be9fd"
        white               = "#f8f8f2"
        brightBlack         = "#6272a4"
        brightRed           = "#ff6e6e"
        brightGreen         = "#69ff94"
        brightYellow        = "#ffffa5"
        brightBlue          = "#d6acff"
        brightPurple        = "#ff92df"
        brightCyan          = "#a4ffff"
        brightWhite         = "#ffffff"
    }
}
